import type { Recipe } from "./types";

export const MOCK_RECIPES: Recipe[] = [
  {
    id: "r_001",
    name: "青椒肉丝",
    ingredients: [
      "猪里脊 200g",
      "青椒 2 个",
      "蒜 2 瓣",
      "生抽 1 勺",
      "淀粉 少许",
      "盐 适量",
    ],
    coreIngredients: ["猪里脊", "青椒", "蒜"],
    optionalIngredients: ["生抽", "淀粉", "盐"],
    steps: [
      "里脊切丝，加少许盐、生抽、淀粉抓匀，腌 10 分钟。",
      "青椒切丝，蒜切片。",
      "热锅少油，下肉丝快速滑散变色盛出。",
      "下蒜片爆香，加入青椒丝翻炒至断生。",
      "倒回肉丝，少量生抽调味，快速翻炒出锅。",
    ],
    tags: ["家常", "快手", "下饭", "炒"],
    timeMinutes: 20,
    difficulty: "easy",
    nutritionTags: ["high_protein"],
    allergenTags: [],
    constraintTags: [],
    matchedInventory: [],
    missingIngredients: [],
    videoReference: null,
  },
  {
    id: "r_002",
    name: "番茄炒蛋",
    ingredients: ["番茄 2 个", "鸡蛋 3 个", "葱 少许", "盐 适量", "糖 少许（可选）"],
    coreIngredients: ["番茄", "鸡蛋"],
    optionalIngredients: ["葱", "盐", "糖"],
    steps: [
      "番茄切块，鸡蛋加少许盐打散。",
      "热锅下油，倒入蛋液炒到凝固成块盛出。",
      "下葱花爆香，加入番茄翻炒出汁。",
      "倒回鸡蛋，按口味加盐（可选少许糖提鲜），翻匀出锅。",
    ],
    tags: ["家常", "快手", "酸甜", "炒"],
    timeMinutes: 15,
    difficulty: "easy",
    nutritionTags: ["balanced"],
    allergenTags: ["egg"],
    constraintTags: [],
    matchedInventory: [],
    missingIngredients: [],
    videoReference: null,
  },
  {
    id: "r_003",
    name: "鱼香茄子",
    ingredients: [
      "茄子 2 根",
      "猪肉末 80g（可选）",
      "蒜 3 瓣",
      "姜 少许",
      "郫县豆瓣 1 勺",
      "生抽 1 勺",
      "醋 1 勺",
      "糖 1 小勺（可选）",
      "淀粉水 适量",
    ],
    coreIngredients: ["茄子", "蒜", "姜", "郫县豆瓣"],
    optionalIngredients: ["猪肉末", "生抽", "醋", "糖", "淀粉水"],
    steps: [
      "茄子切条/块，少油煎软或过油备用。",
      "蒜姜切末，热锅少油下豆瓣炒出红油。",
      "加入肉末炒散（可选），再下茄子翻匀。",
      "加入生抽、醋调味（可选少许糖），加少量水焖 2-3 分钟。",
      "淋入淀粉水收汁，出锅。",
    ],
    tags: ["川味", "下饭", "偏辣", "炒", "家常"],
    timeMinutes: 25,
    difficulty: "medium",
    nutritionTags: ["vegetable_forward"],
    allergenTags: [],
    constraintTags: [],
    matchedInventory: [],
    missingIngredients: [],
    videoReference: null,
  },
];

export function getRecipeById(id: string): Recipe | undefined {
  return MOCK_RECIPES.find((r) => r.id === id);
}
